#pragma once

// Auto-generated by benchmarks/tune_moe_fwd_bwd — wrapper for single-GPU (n_pes == 1) tuned tables.
// Compute is the top-level lookup key. Each compute-specific config subtable
// lives in its own header so Hopper and Blackwell tuning can evolve independently.

#include "moe_fwd_bwd_tuning_config_types.cuh"
#include "moe_fwd_bwd_tuning_configs_single_sm90.cuh"
#include "moe_fwd_bwd_tuning_configs_single_sm100.cuh"

namespace liger {

static constexpr TunedConfigFwdBwdTable kTunedConfigTablesSingle[] = {
	{90,  kTunedConfigsSingleSm90,  kNumTunedConfigsSingleSm90},
	{100, kTunedConfigsSingleSm100, kNumTunedConfigsSingleSm100},
};

static constexpr int kNumTunedConfigTablesSingle =
	sizeof(kTunedConfigTablesSingle) / sizeof(kTunedConfigTablesSingle[0]);

static constexpr int kNumTunedConfigsSingle =
	kNumTunedConfigsSingleSm90 + kNumTunedConfigsSingleSm100;

} // namespace liger
