#pragma once

// Auto-generated by benchmarks/tune_moe_fwd_bwd — wrapper for multi-GPU (n_pes > 1) tuned tables.
// Compute is the top-level lookup key. Each compute-specific config subtable
// lives in its own header so Hopper and Blackwell tuning can evolve independently.

#include "moe_fwd_bwd_tuning_config_types.cuh"
#include "moe_fwd_bwd_tuning_configs_multi_sm90.cuh"
#include "moe_fwd_bwd_tuning_configs_multi_sm100.cuh"

namespace liger {

static constexpr TunedConfigFwdBwdTable kTunedConfigTablesMulti[] = {
	{90,  kTunedConfigsMultiSm90,  kNumTunedConfigsMultiSm90},
	{100, kTunedConfigsMultiSm100, kNumTunedConfigsMultiSm100},
};

static constexpr int kNumTunedConfigTablesMulti =
	sizeof(kTunedConfigTablesMulti) / sizeof(kTunedConfigTablesMulti[0]);

static constexpr int kNumTunedConfigsMulti =
	kNumTunedConfigsMultiSm90 + kNumTunedConfigsMultiSm100;

} // namespace liger
