name: 🐛 Bug Report
description: Create a report to help us reproduce and fix the bug

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/linkedin/Liger-Kernel/issues).
- type: textarea
  attributes:
    label: 🐛 Describe the bug
    description: |
      Please provide a clear and concise description of what the bug is.
    placeholder: |
      A clear and concise description of what the bug is.
  validations:
    required: true

- type: textarea
  attributes:
    label: Reproduce
    description: |
      If applicable, add a minimal example so that we can reproduce the error by running the code.
      The snippet needs to be as succinct (minimal) as possible, so please take time to trim down any irrelevant code to help us debug efficiently.
      We are going to copy-paste your code and we expect to get the same result as you did: avoid any external data, and include the relevant imports, etc.
      If the code is too long (hopefully, it isn't), feel free to put it in a public gist and link it in the issue: https://gist.github.com.
      Please also paste or describe the results you observe instead of the expected results.
      If you observe an error, please paste the error message including the **full** traceback of the exception.
  validations:
    required: false

- type: textarea
  attributes:
    label: Versions
    description: |
      Please provide triton, torch, hardware, and other necessary versions to reproduce the bug.

      For convenience, you can run the following command to get the versions of important software dependencies:
      ```bash
      python -m liger_kernel.env_report
      ```
  validations:
    required: true

- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
