name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Build documentation
        env:
          INPUT_DOCS-FOLDER: "docs/source"  # Adjust if conf.py is in a different folder
          INPUT_BUILD-COMMAND: "make html"
        run: |
          make -C docs/ clean html || exit 1
